test: make replacing space with newlines bit more robust
so we do not add extra random lines where there are multiple spaces, but
also try to avoid bad input.

(cherry picked from commit 67ca156b1c02627cfd6ba73c1d0db00575b1a84f)

diff --git a/.github/actions/compose/action.yml b/.github/actions/compose/action.yml
--- a/.github/actions/compose/action.yml
+++ b/.github/actions/compose/action.yml
@@ -51,12 +51,19 @@ runs:
       id: multi_line_services
       if: ${{ inputs.services != '' }}
       shell: bash
+      env:
+        SERVICES: ${{ inputs.services }}
       run: |
+        services=$(echo "${SERVICES}" | tr -s '[:space:]' '\n' | sed '/^$/d')
+        if grep -qx "EOF" <<< "${services}"; then
+          echo "::error::services input must not contain 'EOF'"
+          exit 1
+        fi
         {
           echo "services<<EOF"
-          echo "${{ inputs.services }}" | tr ' ' '\n'
+          echo "${services}"
           echo "EOF"
-        } >> $GITHUB_OUTPUT
+        } >> "$GITHUB_OUTPUT"
 
     - name: Run ${{ inputs.project_name }} compose
       uses: hoverkraft-tech/compose-action@4894d2492015c1774ee5a13a95b1072093087ec3 # v2.5.0
