test: make replacing space with newlines bit more robust
so we do not add extra random lines where there are multiple spaces, but
also try to avoid bad input.

diff --git a/.github/actions/compose/action.yml b/.github/actions/compose/action.yml
--- a/.github/actions/compose/action.yml
+++ b/.github/actions/compose/action.yml
@@ -51,12 +51,19 @@ runs:
       id: multi_line_services
       if: ${{ inputs.services != '' }}
       shell: bash
+      env:
+        SERVICES: ${{ inputs.services }}
       run: |
+        services=$(echo "${SERVICES}" | tr -s '[:space:]' '\n' | sed '/^$/d')
+        if grep -qx "EOF" <<< "${services}"; then
+          echo "::error::services input must not contain 'EOF'"
+          exit 1
+        fi
         {
           echo "services<<EOF"
-          echo "${{ inputs.services }}" | tr ' ' '\n'
+          echo "${services}"
           echo "EOF"
-        } >> $GITHUB_OUTPUT
+        } >> "$GITHUB_OUTPUT"
 
     - name: Run ${{ inputs.project_name }} compose
       uses: hoverkraft-tech/compose-action@11beaa1c2dae4e8ed7b1665aa074723b6cecb0e4 # v3.0.0
