wip

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -57,7 +57,7 @@ jobs:
     if: failure()
     steps:
       - id: notify-message
-        run: echo "BUILD_OUTPUT_FILE_PATH=${{ (needs.check-results.outputs.hasCanceled && 'canceled') || (needs.check-results.outputs.hasFailed && 'failed') || 'wtf' }}" >> $GITHUB_ENV
+        run: echo "RESULT=${{ ((needs.check-results.outputs.hasCanceled && 'canceled') || (needs.check-results.outputs.hasFailed && 'failed')) || 'wtf' }}" >> $GITHUB_ENV
 
       - id: slack-notify
         name: Send slack notification
@@ -66,7 +66,7 @@ jobs:
           # For posting a rich message using Block Kit
           payload: |
             {
-              "text": ":alarm: CHRIS IS TESTING SOMETHING Build on `main` failed! :alarm:\n${{ github.event.head_commit.url }}",
+              "text": ":alarm: CHRIS IS TESTING SOMETHING Build on `main` ${{ env.RESULT }} failed! :alarm:\n${{ github.event.head_commit.url }}",
              	"blocks": [
                 {
                   "type": "section",
