ci: use re-usable testbench workflow for qa

diff --git a/.github/workflows/qa-testbench.yaml b/.github/workflows/qa-testbench.yaml
--- a/.github/workflows/qa-testbench.yaml
+++ b/.github/workflows/qa-testbench.yaml
@@ -25,50 +25,50 @@ on:
         default: 'main'
         required: false
         type: string
-env:
-  BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
-  GENERATION_TEMPLATE: ${{ inputs.generation }}
-  BRANCH_NAME: ${{ inputs.branch }}
 
 jobs:
-  qa-testbench:
-    name: QA Testbench run
+  checkout:
+    name: checkout
     runs-on: ubuntu-latest
-    timeout-minutes: 45
-    env:
-      IMAGE: "gcr.io/zeebe-io/zeebe"
-      GENERATION_TEMPLATE: "${{ inputs.generation }}"
-      BRANCH_NAME: "${{ inputs.branch }}"
-      ZEEBE_AUTHORIZATION_SERVER_URL: 'https://login.cloud.ultrawombat.com/oauth/token'
-      ZEEBE_CLIENT_ID: 'S7GNoVCE6J-8L~OdFiI59kWM19P.wvKo'
-
     steps:
-      # Since we have branches like stable/1.0 where we have to replace certain patterns, in order to use the branch name as docker image tag
-      - id: set-branch-name
-        name: Sanitize branch name
-        run: |
-          branch=${BRANCH_NAME/\//-}
-          branch=${branch//\./-}
-          branch=${branch:-main}
-          echo "BRANCH=$branch" >> $GITHUB_ENV
-      # We need to check out the evaluated branch and setup java (incl. maven), so we can retrieve the current project version
-      # The version is necessary, since CC Saas only accepts SemVer for docker image tags (need to start with a version tag)
       - uses: actions/checkout@v3
         with:
-          ref: "${{ env.BRANCH_NAME }}"
-      - uses: actions/setup-java@v3.9.0
-        with:
-          distribution: 'temurin'
-          java-version: '17'
-      # Set further environment variables, which are needed for the QA Testbench run
-      - id: set-env
-        name: Set environment variables
-        run: |
-          version=$(mvn help:evaluate -q -DforceStdout -D"expression=project.version")
-          tag="$version-$BRANCH-${GITHUB_SHA::8}"
-          echo "TAG=$tag" >> $GITHUB_ENV
-          echo "QA_RUN_VARIABLES={\"zeebeImage\": \"$IMAGE:$tag\", \"generationTemplate\": \"$GENERATION_TEMPLATE\", \"channel\": \"Internal Dev\", \"branch\": \"$BRANCH_NAME\", \"build\": \"$BUILD_URL\", \"businessKey\": \"$BUILD_URL\", \"processId\": \"qa-protocol\"}" >> $GITHUB_ENV
-          echo "BUSINESS_KEY=$BUILD_URL" >> $GITHUB_ENV
+          ref: "${{ github.ref_name || 'main' }}"
+
+  prepare:
+    # variables in qa job cannot read env variable. So we are building buildUrl here as output so it can be re-used in both qa, wait and notify jobs
+    name: prepare
+    runs-on: ubuntu-latest
+    outputs:
+      buildUrl: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+    steps:
+      - name: prepare variables
+        id: generate
+        run: exit 0
+
+  qa:
+    needs: [checkout, prepare]
+    name: Run testbench process
+    uses: ./.github/workflows/testbench.yaml
+    with:
+      processId: external-tool-integration
+      variables: >
+        {
+        \"zeebeImage\": \"$IMAGE\",
+        \"generationTemplate\": \"${{ inputs.generation }}\",
+        \"channel\": \"Internal Dev\",
+        \"branch\": \"${{ inputs.branch }}\",
+        \"build\":  \"${{ needs.prepare.outputs.buildUrl }}\",
+        \"businessKey\": \"${{ needs.prepare.outputs.buildUrl }}\",
+        \"processId\": \"qa-protocol\"
+        }
+    secrets: inherit
+
+  wait:
+    needs: [qa, prepare]
+    name: Wait until test is completed
+    runs-on: ubuntu-latest
+    steps:
       - name: Import Secrets
         id: secrets
         uses: hashicorp/vault-action@v2.4.3
@@ -78,35 +78,56 @@ jobs:
           roleId: ${{ secrets.VAULT_ROLE_ID }}
           secretId: ${{ secrets.VAULT_SECRET_ID }}
           secrets: |
-            secret/data/products/zeebe/ci/zeebe ZEEBE_GCR_SERVICEACCOUNT_JSON;
             secret/data/products/zeebe/ci/zeebe TESTBENCH_PROD_CLIENT_SECRET;
             secret/data/products/zeebe/ci/zeebe TESTBENCH_PROD_CONTACT_POINT;
-      - name: Login to GCR
-        uses: docker/login-action@v2
-        with:
-          registry: gcr.io
-          username: _json_key
-          password: ${{ steps.secrets.outputs.ZEEBE_GCR_SERVICEACCOUNT_JSON }}
-      - uses: ./.github/actions/setup-zeebe
-      - uses: ./.github/actions/build-zeebe
-        id: build-zeebe
-      - uses: ./.github/actions/build-docker
-        with:
-          repository: ${{ env.IMAGE }}
-          version: ${{ env.TAG }}
-          push: true
-          distball: ${{ steps.build-zeebe.outputs.distball }}
-        # Executes the Testbench QA run and awaits the result
-      - name: Run Testbench QA
-        run: .ci/scripts/distribution/qa-testbench.sh
+
+      - run: |
+          businessKey="${{ env.BUILD_URL }}"
+
+          echo "Waiting for result of $businessKey"
+          jobKey=""
+
+          while true; do
+            # activate jobs non-zero exits can be ignored with `<command> || true`
+            "${zbctl}" activate jobs "$businessKey" > activationresponse.txt 2>/dev/null || true
+            jobKey=$(jq -r '.jobs[0].key' < activationresponse.txt)
+
+            if [[ -z "$jobKey" || "$jobKey" == "null" ]]; then
+              echo "Still waiting"
+              sleep 5m
+            else
+              echo "QA run completed"
+              break
+            fi
+          done
+
+          echo "Job key is: $jobKey"
+          variables=$(jq -r '.jobs[0].variables' < activationresponse.txt)
+          echo "Job variables are: $variables"
+
+          testResult=$(echo "$variables" | jq -r '.aggregatedTestResult')
+          echo "Test result is: $testResult"
+
+          "${zbctl}" complete job "$jobKey"
+
+          if [ "$testResult" == "FAILED" ]; then
+            echo "Test failed"
+            exit 1
+          else
+            echo "Test passed or skipped"
+            exit 0
+          fi
         env:
           ZEEBE_CLIENT_SECRET: ${{ steps.secrets.outputs.TESTBENCH_PROD_CLIENT_SECRET }}
           ZEEBE_ADDRESS: ${{ steps.secrets.outputs.TESTBENCH_PROD_CONTACT_POINT }}
+          ZEEBE_AUTHORIZATION_SERVER_URL: 'https://login.cloud.ultrawombat.com/oauth/token'
+          ZEEBE_CLIENT_ID: 'S7GNoVCE6J-8L~OdFiI59kWM19P.wvKo'
+          BUILD_URL: ${{ needs.prepare.outputs.buildUrl }}
 
   notify:
     name: Send slack notification
     runs-on: ubuntu-latest
-    needs: [qa-testbench]
+    needs: [ wait, prepare ]
     if: ${{ always() }}
     steps:
       - id: slack-failure-notify
@@ -116,20 +137,20 @@ jobs:
         with:
           payload: |
             {
-              "text": ":alarm: QA run on `${{ env.BRANCH_NAME }}` with generation template `${{ env.GENERATION_TEMPLATE }}` failed! :alarm:\n ${{ env.BUILD_URL }}",
+              "text": ":alarm: QA run on `${{ inputs.branch }}` with generation template `${{ inputs.generation }}` failed! :alarm:\n ${{ needs.prepare.outputs.buildUrl }}",
              	"blocks": [
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
-                    "text": ":alarm: QA run on `${{ env.BRANCH_NAME }}` with generation template `${{ env.GENERATION_TEMPLATE }}` failed! :alarm:"
+                    "text": ":alarm: QA run on `${{ inputs.branch }}` with generation template `${{ inputs.generation }}` failed! :alarm:"
                   }
                 },
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
-                    "text": "Please check: ${{ env.BUILD_URL }}\n \\cc @zeebe-medic"
+                    "text": "Please check: ${{ needs.prepare.outputs.buildUrl }}\n \\cc @zeebe-medic"
                   }
                 }
               ]
@@ -145,13 +166,13 @@ jobs:
         with:
           payload: |
             {
-              "text": ":tada: QA run succeeded on `${{ env.BRANCH_NAME }}` with generation template `${{ env.GENERATION_TEMPLATE }}`! :tada:\n ${{ env.BUILD_URL }}",
+              "text": ":tada: QA run succeeded on `${{ inputs.branch }}` with generation template `${{ inputs.generation }}`! :tada:\n ${{ needs.prepare.outputs.buildUrl }}",
              	"blocks": [
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
-                    "text": ":tada: QA run succeeded on `${{ env.BRANCH_NAME }}` with generation template `${{ env.GENERATION_TEMPLATE }}`! :tada:"
+                    "text": ":tada: QA run succeeded on `${{ inputs.branch }}` with generation template `${{ inputs.generation }}`! :tada:"
                   }
                 },
                 {
