refactor: add Snyk release job
(cherry picked from commit c3544019243b065d34f5c066f8d12bef7e735978)

diff --git a/.github/workflows/snyk.yml b/.github/workflows/snyk.yml
--- a/.github/workflows/snyk.yml
+++ b/.github/workflows/snyk.yml
@@ -27,6 +27,11 @@ on:
         required: false
         type: boolean
         default: true
+      useMinorVersion:
+        description: Uses the major and minor version only for target and version
+        required: false
+        type: boolean
+        default: false
   workflow_call:
     secrets:
       SNYK_TOKEN:
@@ -54,6 +59,11 @@ on:
         required: false
         type: boolean
         default: true
+      useMinorVersion:
+        description: Uses the major and minor version only for target and version
+        required: false
+        type: boolean
+        default: false
 
 defaults:
   run:
@@ -104,6 +114,10 @@ jobs:
 
           # use inputs.dockerImage if present; otherwise if building, use the output of the build step; otherwise infer from version and default repository camunda/zeebe
           export DOCKER_IMAGE=$([[ ! -z '${{ inputs.dockerImage }}' ]] && echo '${{ inputs.dockerImage }}' || ([[ '${{ inputs.build }}' == 'true' ]] && echo '${{ steps.build-docker.outputs.image }}' || echo "camunda/zeebe:${VERSION}"))
+
+          if [[ '${{ inputs.useMinorVersion }}' == 'true' ]]; then
+            export TARGET="$(echo $VERSION | sed -E -e 's/\.[^.]*$//')"
+          fi
 
           echo "SNYK_ARGS=" \
             "--show-vulnerable-paths=all" \
@@ -157,7 +171,13 @@ jobs:
           # feature at the moment. It's added here anyway for now, and hopefully support will come soon.
           PROJECT_NAME="zeebe(${TARGET}):Dockerfile"
           snyk container "${SNYK_COMMAND}" "${DOCKER_IMAGE}" --file=Dockerfile "'--project-name=${PROJECT_NAME}'" ${SNYK_ARGS} "$(output "${SARIF}" 'docker')" || exitCode=1
-          exit "${exitCode}"
+
+          # Only fail if we entirely failed to parse the projects
+          if [[ $exitCode -ge 1 ]]; then
+            exit "${exitCode}"
+          else
+            exit 0
+          fi
       # This makes the result of our test available in GitHub Code Scanning (look for the Snyk tools)
       # You can filter by your PR ID, by branch, etc.
       # This step is only executed if we're testing, as otherwise no SARIF files are emitted
